name: Java Associative Property Check

on:
  push:
    branches:
      - main
      - floating-point-order-change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t associative-property-check .

      - name: Run Docker container and generate results
        run: docker run associative-property-check > answer_associativity.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: associative-property-results
          path: answer_associativity.txt

      - name: Commit and push the results to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add answer_associativity.txt
          git commit -m "Update associative property results"
          git push https://alpjakop:${{ secrets.PAT_TOKEN }}@github.com/alpjakop/REP/

  generate-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Java program
        run: javac src/PropertyCheck.java

      - name: Run Java program with runtime parameters
        env:
          REPETITIONS_LIST: "500,1000,2000"  # This can be modified as per your needs
          SAMPLE_SIZE: "3"                   # Define sample size (0 for no sampling)
        run: java -cp src PropertyCheck

      - name: Upload CSV results
        uses: actions/upload-artifact@v4
        with:
          name: variability-factor-results
          path: results.csv

      - name: Commit and push CSV results to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add results.csv
          git commit -m "Update variability factor results"
          git push https://alpjakop:${{ secrets.PAT_TOKEN }}@github.com/alpjakop/REP/
