name: Java Associative Property Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t associative-property-check .

      - name: Run Docker container and save output
        run: docker run associative-property-check > serialized/pushed/answer_associativity.txt

      # Commit the results to the repository
      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add serialized/pushed/answer_associativity.txt
          git commit -m "Update answer_associativity.txt with latest results"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
