name: Java Associative Property Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t associative-property-check .

      - name: Run Docker container and generate results
        run: docker run associative-property-check > answer_associativity.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: associative-property-results
          path: answer_associativity.txt

      - name: Commit and push the results to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add answer_associativity.txt
          git commit -m "Update associative property results"
          git push https://alpjakop:${{ secrets.PAT_TOKEN }}@github.com/alpjakop/REP.git
