name: Python CI

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # If you have dependencies

    - name: Run the parameterized script
      run: |
        python parameterized.py  # Ensure this points to your script's name

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: results.csv

    - name: Commit and push the results to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add results.csv
          git commit -m "Update Results from Runtime Parameter Based Approach"
          git push https://alpjakop:${{ secrets.PAT_TOKEN }}@github.com/alpjakop/REP/